// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LearningManagementSystem.Data.LMSModels;

public partial class LearningManagementContext : DbContext
{
    public LearningManagementContext()
    {
    }

    public LearningManagementContext(DbContextOptions<LearningManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<QuizType> QuizTypes { get; set; }

    public virtual DbSet<Trainer> Trainers { get; set; }

    public virtual DbSet<Training> Training { get; set; }

    public virtual DbSet<TrainingCourse> TrainingCourses { get; set; }

    public virtual DbSet<TrainingCourseModule> TrainingCourseModules { get; set; }

    public virtual DbSet<TrainingCourseModuleResource> TrainingCourseModuleResources { get; set; }

    public virtual DbSet<TrainingParticipant> TrainingParticipants { get; set; }

    public virtual DbSet<TrainingParticipantDeletedReason> TrainingParticipantDeletedReasons { get; set; }

    public virtual DbSet<TrainingParticipantTransfer> TrainingParticipantTransfers { get; set; }

    public virtual DbSet<TrainingQuestion> TrainingQuestions { get; set; }

    public virtual DbSet<TrainingQuestionAnswer> TrainingQuestionAnswers { get; set; }

    public virtual DbSet<TrainingQuestionAttempt> TrainingQuestionAttempts { get; set; }

    public virtual DbSet<TrainingQuestionCorrectAnswer> TrainingQuestionCorrectAnswers { get; set; }

    public virtual DbSet<TrainingQuiz> TrainingQuizzes { get; set; }

    public virtual DbSet<TrainingQuizAttempt> TrainingQuizAttempts { get; set; }

    public virtual DbSet<TrainingResourcesWatchStatus> TrainingResourcesWatchStatuses { get; set; }

    public virtual DbSet<TrainingShedule> TrainingShedules { get; set; }

    public virtual DbSet<TrainingStatus> TrainingStatuses { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=VF-CO-IT-DEV-02;Initial Catalog=LearningManagement;User ID=sa;Password=1234567890;Encrypt=True;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<QuizType>(entity =>
        {
            entity.ToTable("QuizType");

            entity.Property(e => e.QuizTypeId).HasColumnName("QuizType_Id");
            entity.Property(e => e.QuizTypeActive).HasColumnName("QuizType_Active");
            entity.Property(e => e.QuizTypeCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("QuizType_CreatedDate");
            entity.Property(e => e.QuizTypeType)
                .HasMaxLength(20)
                .HasColumnName("QuizType_Type");
        });

        modelBuilder.Entity<Trainer>(entity =>
        {
            entity.ToTable("Trainer");

            entity.Property(e => e.TrainerId).HasColumnName("Trainer_Id");
            entity.Property(e => e.TrainerActive).HasColumnName("Trainer_Active");
            entity.Property(e => e.TrainerCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("Trainer_CreatedDate");
            entity.Property(e => e.TrainerDepartment)
                .HasMaxLength(100)
                .HasColumnName("Trainer_Department");
            entity.Property(e => e.TrainerDesignation)
                .HasMaxLength(100)
                .HasColumnName("Trainer_Designation");
            entity.Property(e => e.TrainerEpf)
                .HasMaxLength(6)
                .HasColumnName("Trainer_EPF");
            entity.Property(e => e.TrainerFname)
                .HasMaxLength(10)
                .HasColumnName("Trainer_FName");
            entity.Property(e => e.TrainerLname)
                .HasMaxLength(10)
                .HasColumnName("Trainer_LName");
            entity.Property(e => e.TrainerType)
                .HasMaxLength(50)
                .HasColumnName("Trainer_Type");
        });

        modelBuilder.Entity<Training>(entity =>
        {
            entity.Property(e => e.TrainingId).HasColumnName("Training_Id");
            entity.Property(e => e.TrainingActive).HasColumnName("Training_Active");
            entity.Property(e => e.TrainingCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("Training_CreatedDate");
            entity.Property(e => e.TrainingDescription).HasColumnName("Training_Description");
            entity.Property(e => e.TrainingEname)
                .HasMaxLength(100)
                .HasColumnName("Training_EName");
            entity.Property(e => e.TrainingSname)
                .HasMaxLength(100)
                .HasColumnName("Training_SName");
            entity.Property(e => e.TrainingTname)
                .HasMaxLength(100)
                .HasColumnName("Training_TName");
            entity.Property(e => e.TrainingType)
                .HasMaxLength(15)
                .HasColumnName("Training_Type");
        });

        modelBuilder.Entity<TrainingCourse>(entity =>
        {
            entity.ToTable("TrainingCourse");

            entity.Property(e => e.TrainingCourseId).HasColumnName("TrainingCourse_Id");
            entity.Property(e => e.TrainingCourseActive).HasColumnName("TrainingCourse_Active");
            entity.Property(e => e.TrainingCourseCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingCourse_CreatedDate");
            entity.Property(e => e.TrainingCourseDescription).HasColumnName("TrainingCourse_Description");
            entity.Property(e => e.TrainingCourseEname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourse_EName");
            entity.Property(e => e.TrainingCourseSequance).HasColumnName("TrainingCourse_Sequance");
            entity.Property(e => e.TrainingCourseSname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourse_SName");
            entity.Property(e => e.TrainingCourseTname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourse_TName");
            entity.Property(e => e.TrainingCourseTrainerId).HasColumnName("TrainingCourse_TrainerId");
            entity.Property(e => e.TrainingCourseTrainingId).HasColumnName("TrainingCourse_TrainingId");

            entity.HasOne(d => d.TrainingCourseTrainer).WithMany(p => p.TrainingCourses)
                .HasForeignKey(d => d.TrainingCourseTrainerId)
                .HasConstraintName("FK_TrainingCourse_Trainer");

            entity.HasOne(d => d.TrainingCourseTraining).WithMany(p => p.TrainingCourses)
                .HasForeignKey(d => d.TrainingCourseTrainingId)
                .HasConstraintName("FK_TrainingCourse_Training");
        });

        modelBuilder.Entity<TrainingCourseModule>(entity =>
        {
            entity.ToTable("TrainingCourseModule");

            entity.Property(e => e.TrainingCourseModuleId).HasColumnName("TrainingCourseModule_Id");
            entity.Property(e => e.TrainingCourseModuleActive).HasColumnName("TrainingCourseModule_Active");
            entity.Property(e => e.TrainingCourseModuleCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingCourseModule_CreatedDate");
            entity.Property(e => e.TrainingCourseModuleDescription).HasColumnName("TrainingCourseModule_Description");
            entity.Property(e => e.TrainingCourseModuleEname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourseModule_EName");
            entity.Property(e => e.TrainingCourseModuleIsQuiz).HasColumnName("TrainingCourseModule_IsQuiz");
            entity.Property(e => e.TrainingCourseModuleQuizTypeId).HasColumnName("TrainingCourseModule_QuizTypeId");
            entity.Property(e => e.TrainingCourseModuleSequance).HasColumnName("TrainingCourseModule_Sequance");
            entity.Property(e => e.TrainingCourseModuleSname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourseModule_SName");
            entity.Property(e => e.TrainingCourseModuleTname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourseModule_TName");
            entity.Property(e => e.TrainingCourseModuleTrainingCourseId).HasColumnName("TrainingCourseModule_TrainingCourseId");

            entity.HasOne(d => d.TrainingCourseModuleQuizType).WithMany(p => p.TrainingCourseModules)
                .HasForeignKey(d => d.TrainingCourseModuleQuizTypeId)
                .HasConstraintName("FK_TrainingCourseModule_QuizType");

            entity.HasOne(d => d.TrainingCourseModuleTrainingCourse).WithMany(p => p.TrainingCourseModules)
                .HasForeignKey(d => d.TrainingCourseModuleTrainingCourseId)
                .HasConstraintName("FK_TrainingCourseModule_TrainingCourse");
        });

        modelBuilder.Entity<TrainingCourseModuleResource>(entity =>
        {
            entity.HasKey(e => e.TrainingCourseModuleResourcesId);

            entity.Property(e => e.TrainingCourseModuleResourcesId).HasColumnName("TrainingCourseModuleResources_Id");
            entity.Property(e => e.TrainingCourseModuleResourcesActive).HasColumnName("TrainingCourseModuleResources_Active");
            entity.Property(e => e.TrainingCourseModuleResourcesCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingCourseModuleResources_CreatedDate");
            entity.Property(e => e.TrainingCourseModuleResourcesDescription).HasColumnName("TrainingCourseModuleResources_Description");
            entity.Property(e => e.TrainingCourseModuleResourcesEname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourseModuleResources_EName");
            entity.Property(e => e.TrainingCourseModuleResourcesIsOtherResource).HasColumnName("TrainingCourseModuleResources_IsOtherResource");
            entity.Property(e => e.TrainingCourseModuleResourcesLanguageId).HasColumnName("TrainingCourseModuleResources_LanguageId");
            entity.Property(e => e.TrainingCourseModuleResourcesLength).HasColumnName("TrainingCourseModuleResources_Length");
            entity.Property(e => e.TrainingCourseModuleResourcesModuleId).HasColumnName("TrainingCourseModuleResources_ModuleId");
            entity.Property(e => e.TrainingCourseModuleResourcesPath)
                .HasMaxLength(500)
                .HasColumnName("TrainingCourseModuleResources_Path");
            entity.Property(e => e.TrainingCourseModuleResourcesSequance).HasColumnName("TrainingCourseModuleResources_Sequance");
            entity.Property(e => e.TrainingCourseModuleResourcesSname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourseModuleResources_SName");
            entity.Property(e => e.TrainingCourseModuleResourcesTname)
                .HasMaxLength(150)
                .HasColumnName("TrainingCourseModuleResources_TName");
            entity.Property(e => e.TrainingCourseModuleResourcesType)
                .HasMaxLength(50)
                .HasColumnName("TrainingCourseModuleResources_Type");

            entity.HasOne(d => d.TrainingCourseModuleResourcesModule).WithMany(p => p.TrainingCourseModuleResources)
                .HasForeignKey(d => d.TrainingCourseModuleResourcesModuleId)
                .HasConstraintName("FK_TrainingCourseModuleResources_TrainingCourseModule");
        });

        modelBuilder.Entity<TrainingParticipant>(entity =>
        {
            entity.ToTable("TrainingParticipant");

            entity.Property(e => e.TrainingParticipantId).HasColumnName("TrainingParticipant_Id");
            entity.Property(e => e.TrainingParticipantActive).HasColumnName("TrainingParticipant_Active");
            entity.Property(e => e.TrainingParticipantDeletedReasonId).HasColumnName("TrainingParticipant_DeletedReasonId");
            entity.Property(e => e.TrainingParticipantDepartment)
                .HasMaxLength(50)
                .HasColumnName("TrainingParticipant_Department");
            entity.Property(e => e.TrainingParticipantDesignation)
                .HasMaxLength(50)
                .HasColumnName("TrainingParticipant_Designation");
            entity.Property(e => e.TrainingParticipantEmail)
                .HasMaxLength(150)
                .HasColumnName("TrainingParticipant_Email");
            entity.Property(e => e.TrainingParticipantEpf)
                .HasMaxLength(10)
                .HasColumnName("TrainingParticipant_EPF");
            entity.Property(e => e.TrainingParticipantFname)
                .HasMaxLength(10)
                .HasColumnName("TrainingParticipant_FName");
            entity.Property(e => e.TrainingParticipantIsTransfered).HasColumnName("TrainingParticipant_IsTransfered");
            entity.Property(e => e.TrainingParticipantLname)
                .HasMaxLength(10)
                .HasColumnName("TrainingParticipant_LName");
            entity.Property(e => e.TrainingParticipantTrainingSheduleId).HasColumnName("TrainingParticipant_TrainingSheduleId");

            entity.HasOne(d => d.TrainingParticipantDeletedReason).WithMany(p => p.TrainingParticipants)
                .HasForeignKey(d => d.TrainingParticipantDeletedReasonId)
                .HasConstraintName("FK_TrainingParticipant_TrainingParticipantDeletedReason");

            entity.HasOne(d => d.TrainingParticipantTrainingShedule).WithMany(p => p.TrainingParticipants)
                .HasForeignKey(d => d.TrainingParticipantTrainingSheduleId)
                .HasConstraintName("FK_TrainingParticipant_TrainingParticipant");
        });

        modelBuilder.Entity<TrainingParticipantDeletedReason>(entity =>
        {
            entity.HasKey(e => e.TrainingParticipantDeletedRId);

            entity.ToTable("TrainingParticipantDeletedReason");

            entity.Property(e => e.TrainingParticipantDeletedRId).HasColumnName("TrainingParticipantDeletedR_Id");
            entity.Property(e => e.TrainingParticipantDeletedRActive).HasColumnName("TrainingParticipantDeletedR_Active");
            entity.Property(e => e.TrainingParticipantDeletedRCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingParticipantDeletedR_CreatedDate");
            entity.Property(e => e.TrainingParticipantDeletedRReason)
                .HasMaxLength(100)
                .HasColumnName("TrainingParticipantDeletedR_Reason");
        });

        modelBuilder.Entity<TrainingParticipantTransfer>(entity =>
        {
            entity.ToTable("TrainingParticipantTransfer");

            entity.Property(e => e.TrainingParticipantTransferId).HasColumnName("TrainingParticipantTransfer_Id");
            entity.Property(e => e.TrainingParticipantTransferActive).HasColumnName("TrainingParticipantTransfer_Active");
            entity.Property(e => e.TrainingParticipantTransferNewSheduleId).HasColumnName("TrainingParticipantTransfer_NewSheduleId");
            entity.Property(e => e.TrainingParticipantTransferOldShduleid).HasColumnName("TrainingParticipantTransfer_OldShduleid");
            entity.Property(e => e.TrainingParticipantTransferTransferedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingParticipantTransfer_TransferedDate");
        });

        modelBuilder.Entity<TrainingQuestion>(entity =>
        {
            entity.ToTable("TrainingQuestion");

            entity.Property(e => e.TrainingQuestionId).HasColumnName("TrainingQuestion_Id");
            entity.Property(e => e.TrainingQuestionActive).HasColumnName("TrainingQuestion_Active");
            entity.Property(e => e.TrainingQuestionCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingQuestion_CreatedDate");
            entity.Property(e => e.TrainingQuestionEname).HasColumnName("TrainingQuestion_EName");
            entity.Property(e => e.TrainingQuestionQuizId).HasColumnName("TrainingQuestion_QuizId");
            entity.Property(e => e.TrainingQuestionSname).HasColumnName("TrainingQuestion_SName");
            entity.Property(e => e.TrainingQuestionTname).HasColumnName("TrainingQuestion_TName");

            entity.HasOne(d => d.TrainingQuestionQuiz).WithMany(p => p.TrainingQuestions)
                .HasForeignKey(d => d.TrainingQuestionQuizId)
                .HasConstraintName("FK_TrainingQuestion_TrainingQuiz");
        });

        modelBuilder.Entity<TrainingQuestionAnswer>(entity =>
        {
            entity.HasKey(e => e.TrainingQanswerId);

            entity.ToTable("TrainingQuestionAnswer");

            entity.Property(e => e.TrainingQanswerId).HasColumnName("TrainingQAnswer_Id");
            entity.Property(e => e.TrainingQanswerActive).HasColumnName("TrainingQAnswer_Active");
            entity.Property(e => e.TrainingQanswerCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingQAnswer_CreatedDate");
            entity.Property(e => e.TrainingQanswerEname).HasColumnName("TrainingQAnswer_EName");
            entity.Property(e => e.TrainingQanswerQuestionId).HasColumnName("TrainingQAnswer_QuestionId");
            entity.Property(e => e.TrainingQanswerSname).HasColumnName("TrainingQAnswer_SName");
            entity.Property(e => e.TrainingQanswerTname).HasColumnName("TrainingQAnswer_TName");

            entity.HasOne(d => d.TrainingQanswerQuestion).WithMany(p => p.TrainingQuestionAnswers)
                .HasForeignKey(d => d.TrainingQanswerQuestionId)
                .HasConstraintName("FK_TrainingQuestionAnswer_TrainingQuestion");
        });

        modelBuilder.Entity<TrainingQuestionAttempt>(entity =>
        {
            entity.HasKey(e => e.TrainingQattempId);

            entity.ToTable("TrainingQuestionAttempt");

            entity.Property(e => e.TrainingQattempId).HasColumnName("TrainingQAttemp_Id");
            entity.Property(e => e.TrainingQattempParticipantId).HasColumnName("TrainingQAttemp_ParticipantId");
            entity.Property(e => e.TrainingQattempQuestionAnswerId).HasColumnName("TrainingQAttemp_QuestionAnswerId");
            entity.Property(e => e.TrainingQattempQuestionId).HasColumnName("TrainingQAttemp_QuestionId");
            entity.Property(e => e.TrainingQattempQuizAttempId).HasColumnName("TrainingQAttemp_QuizAttempId");
            entity.Property(e => e.TrainingQattempQuizId).HasColumnName("TrainingQAttemp_QuizId");

            entity.HasOne(d => d.TrainingQattempParticipant).WithMany(p => p.TrainingQuestionAttempts)
                .HasForeignKey(d => d.TrainingQattempParticipantId)
                .HasConstraintName("FK_TrainingQuestionAttempt_TrainingParticipant");

            entity.HasOne(d => d.TrainingQattempQuestion).WithMany(p => p.TrainingQuestionAttempts)
                .HasForeignKey(d => d.TrainingQattempQuestionId)
                .HasConstraintName("FK_TrainingQuestionAttempt_TrainingQuestion");

            entity.HasOne(d => d.TrainingQattempQuizAttemp).WithMany(p => p.TrainingQuestionAttempts)
                .HasForeignKey(d => d.TrainingQattempQuizAttempId)
                .HasConstraintName("FK_TrainingQuestionAttempt_TrainingQuizAttempt");

            entity.HasOne(d => d.TrainingQattempQuiz).WithMany(p => p.TrainingQuestionAttempts)
                .HasForeignKey(d => d.TrainingQattempQuizId)
                .HasConstraintName("FK_TrainingQuestionAttempt_TrainingQuiz");
        });

        modelBuilder.Entity<TrainingQuestionCorrectAnswer>(entity =>
        {
            entity.HasKey(e => e.TrainingQcorrectAnswerId).HasName("PK_TrainingQCorrectAnswer");

            entity.ToTable("TrainingQuestionCorrectAnswer");

            entity.Property(e => e.TrainingQcorrectAnswerId)
                .ValueGeneratedOnAdd()
                .HasColumnName("TrainingQCorrectAnswer_Id");
            entity.Property(e => e.TrainingQcorrectAnswerActive).HasColumnName("TrainingQCorrectAnswer_Active");
            entity.Property(e => e.TrainingQcorrectAnswerCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingQCorrectAnswer_CreatedDate");
            entity.Property(e => e.TrainingQcorrectAnswerQanswerId).HasColumnName("TrainingQCorrectAnswer_QAnswerId");
            entity.Property(e => e.TrainingQcorrectAnswerQuestionId).HasColumnName("TrainingQCorrectAnswer_QuestionId");

            entity.HasOne(d => d.TrainingQcorrectAnswer).WithOne(p => p.TrainingQuestionCorrectAnswer)
                .HasForeignKey<TrainingQuestionCorrectAnswer>(d => d.TrainingQcorrectAnswerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrainingQuestionCorrectAnswer_TrainingQuestion");

            entity.HasOne(d => d.TrainingQcorrectAnswerQanswer).WithMany(p => p.TrainingQuestionCorrectAnswers)
                .HasForeignKey(d => d.TrainingQcorrectAnswerQanswerId)
                .HasConstraintName("FK_TrainingQuestionCorrectAnswer_TrainingQuestionAnswer");
        });

        modelBuilder.Entity<TrainingQuiz>(entity =>
        {
            entity.ToTable("TrainingQuiz");

            entity.Property(e => e.TrainingQuizId).HasColumnName("TrainingQuiz_Id");
            entity.Property(e => e.TrainingQuizActive).HasColumnName("TrainingQuiz_Active");
            entity.Property(e => e.TrainingQuizAttemptCount).HasColumnName("TrainingQuiz_AttemptCount");
            entity.Property(e => e.TrainingQuizCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingQuiz_CreatedDate");
            entity.Property(e => e.TrainingQuizEname)
                .HasMaxLength(150)
                .HasColumnName("TrainingQuiz_EName");
            entity.Property(e => e.TrainingQuizModuleId).HasColumnName("TrainingQuiz_ModuleId");
            entity.Property(e => e.TrainingQuizNoOfAnswerRequired).HasColumnName("TrainingQuiz_NoOfAnswerRequired");
            entity.Property(e => e.TrainingQuizSname)
                .HasMaxLength(150)
                .HasColumnName("TrainingQuiz_SName");
            entity.Property(e => e.TrainingQuizTname)
                .HasMaxLength(150)
                .HasColumnName("TrainingQuiz_TName");

            entity.HasOne(d => d.TrainingQuizModule).WithMany(p => p.TrainingQuizzes)
                .HasForeignKey(d => d.TrainingQuizModuleId)
                .HasConstraintName("FK_TrainingQuiz_TrainingCourseModule");
        });

        modelBuilder.Entity<TrainingQuizAttempt>(entity =>
        {
            entity.ToTable("TrainingQuizAttempt");

            entity.Property(e => e.TrainingQuizAttemptId).HasColumnName("TrainingQuizAttempt_Id");
            entity.Property(e => e.TrainingQuizAttemptMarks).HasColumnName("TrainingQuizAttempt_Marks");
            entity.Property(e => e.TrainingQuizAttemptParticipantId).HasColumnName("TrainingQuizAttempt_ParticipantId");
            entity.Property(e => e.TrainingQuizAttemptQuizId).HasColumnName("TrainingQuizAttempt_QuizId");

            entity.HasOne(d => d.TrainingQuizAttemptParticipant).WithMany(p => p.TrainingQuizAttempts)
                .HasForeignKey(d => d.TrainingQuizAttemptParticipantId)
                .HasConstraintName("FK_TrainingQuizAttempt_TrainingParticipant");

            entity.HasOne(d => d.TrainingQuizAttemptQuiz).WithMany(p => p.TrainingQuizAttempts)
                .HasForeignKey(d => d.TrainingQuizAttemptQuizId)
                .HasConstraintName("FK_TrainingQuizAttempt_TrainingQuiz");
        });

        modelBuilder.Entity<TrainingResourcesWatchStatus>(entity =>
        {
            entity.ToTable("TrainingResourcesWatchStatus");

            entity.Property(e => e.TrainingResourcesWatchStatusId).HasColumnName("TrainingResourcesWatchStatus_Id");
            entity.Property(e => e.TrainingResourcesWatchStatusCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingResourcesWatchStatus_CreatedDate");
            entity.Property(e => e.TrainingResourcesWatchStatusParticipantId).HasColumnName("TrainingResourcesWatchStatus_ParticipantId");
            entity.Property(e => e.TrainingResourcesWatchStatusResourceId).HasColumnName("TrainingResourcesWatchStatus_ResourceId");
            entity.Property(e => e.TrainingResourcesWatchStatusStatus).HasColumnName("TrainingResourcesWatchStatus_Status");
            entity.Property(e => e.TrainingResourcesWatchStatusWatchTime)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("TrainingResourcesWatchStatus_WatchTime");

            entity.HasOne(d => d.TrainingResourcesWatchStatusParticipant).WithMany(p => p.TrainingResourcesWatchStatuses)
                .HasForeignKey(d => d.TrainingResourcesWatchStatusParticipantId)
                .HasConstraintName("FK_TrainingResourcesWatchStatus_TrainingParticipant");

            entity.HasOne(d => d.TrainingResourcesWatchStatusResource).WithMany(p => p.TrainingResourcesWatchStatuses)
                .HasForeignKey(d => d.TrainingResourcesWatchStatusResourceId)
                .HasConstraintName("FK_TrainingResourcesWatchStatus_TrainingCourseModuleResources");
        });

        modelBuilder.Entity<TrainingShedule>(entity =>
        {
            entity.ToTable("TrainingShedule");

            entity.Property(e => e.TrainingSheduleId).HasColumnName("TrainingShedule_Id");
            entity.Property(e => e.TrainingSheduleActive).HasColumnName("TrainingShedule_Active");
            entity.Property(e => e.TrainingSheduleCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingShedule_CreatedDate");
            entity.Property(e => e.TrainingSheduleDescription).HasColumnName("TrainingShedule_Description");
            entity.Property(e => e.TrainingSheduleEndDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingShedule_EndDate");
            entity.Property(e => e.TrainingSheduleIsComplete).HasColumnName("TrainingShedule_IsComplete");
            entity.Property(e => e.TrainingSheduleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("TrainingShedule_Name");
            entity.Property(e => e.TrainingSheduleParticipantCount).HasColumnName("TrainingShedule_ParticipantCount");
            entity.Property(e => e.TrainingSheduleStartDate)
                .HasColumnType("datetime")
                .HasColumnName("TrainingShedule_StartDate");
            entity.Property(e => e.TrainingSheduleTrainerId).HasColumnName("TrainingShedule_TrainerId");
            entity.Property(e => e.TrainingSheduleTrainingCourseId).HasColumnName("TrainingShedule_TrainingCourseId");

            entity.HasOne(d => d.TrainingSheduleTrainer).WithMany(p => p.TrainingShedules)
                .HasForeignKey(d => d.TrainingSheduleTrainerId)
                .HasConstraintName("FK_TrainingShedule_Trainer");

            entity.HasOne(d => d.TrainingSheduleTrainingCourse).WithMany(p => p.TrainingShedules)
                .HasForeignKey(d => d.TrainingSheduleTrainingCourseId)
                .HasConstraintName("FK_TrainingShedule_TrainingCourse");
        });

        modelBuilder.Entity<TrainingStatus>(entity =>
        {
            entity.ToTable("TrainingStatus");

            entity.Property(e => e.TrainingStatusId).HasColumnName("TrainingStatus_Id");
            entity.Property(e => e.TrainingStatusCourseId).HasColumnName("TrainingStatus_CourseId");
            entity.Property(e => e.TrainingStatusIsQuizVisibility).HasColumnName("TrainingStatus_IsQuizVisibility");
            entity.Property(e => e.TrainingStatusModuleId).HasColumnName("TrainingStatus_ModuleId");
            entity.Property(e => e.TrainingStatusParticipantId).HasColumnName("TrainingStatus_ParticipantId");
            entity.Property(e => e.TrainingStatusQuizId).HasColumnName("TrainingStatus_QuizId");
            entity.Property(e => e.TrainingStatusTrainingId).HasColumnName("TrainingStatus_TrainingId");

            entity.HasOne(d => d.TrainingStatusCourse).WithMany(p => p.TrainingStatuses)
                .HasForeignKey(d => d.TrainingStatusCourseId)
                .HasConstraintName("FK_TrainingStatus_TrainingCourse");

            entity.HasOne(d => d.TrainingStatusModule).WithMany(p => p.TrainingStatuses)
                .HasForeignKey(d => d.TrainingStatusModuleId)
                .HasConstraintName("FK_TrainingStatus_TrainingCourseModule");

            entity.HasOne(d => d.TrainingStatusQuiz).WithMany(p => p.TrainingStatuses)
                .HasForeignKey(d => d.TrainingStatusQuizId)
                .HasConstraintName("FK_TrainingStatus_TrainingQuiz");

            entity.HasOne(d => d.TrainingStatusTraining).WithMany(p => p.TrainingStatuses)
                .HasForeignKey(d => d.TrainingStatusTrainingId)
                .HasConstraintName("FK_TrainingStatus_Training");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.UserName).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}