// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class QuizType
{
    public int QuizTypeId { get; set; }

    public string QuizTypeType { get; set; }

    public bool? QuizTypeActive { get; set; }

    public DateTime? QuizTypeCreatedDate { get; set; }

    public virtual ICollection<TrainingCourseModule> TrainingCourseModules { get; set; } = new List<TrainingCourseModule>();
}