// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingStatus
{
    public int TrainingStatusId { get; set; }

    public int? TrainingStatusTrainingId { get; set; }

    public int? TrainingStatusCourseId { get; set; }

    public int? TrainingStatusModuleId { get; set; }

    public int? TrainingStatusQuizId { get; set; }

    public int? TrainingStatusParticipantId { get; set; }

    public bool? TrainingStatusIsQuizVisibility { get; set; }

    public virtual TrainingCourse TrainingStatusCourse { get; set; }

    public virtual TrainingCourseModule TrainingStatusModule { get; set; }

    public virtual TrainingQuiz TrainingStatusQuiz { get; set; }

    public virtual Training TrainingStatusTraining { get; set; }
}