// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingQuestionCorrectAnswer
{
    public int TrainingQcorrectAnswerId { get; set; }

    public int? TrainingQcorrectAnswerQanswerId { get; set; }

    public int? TrainingQcorrectAnswerQuestionId { get; set; }

    public bool? TrainingQcorrectAnswerActive { get; set; }

    public DateTime? TrainingQcorrectAnswerCreatedDate { get; set; }

    public virtual TrainingQuestion TrainingQcorrectAnswerQuestion { get; set; }

    public virtual TrainingQuestionAnswer TrainingQcorrectAnswerQanswer { get; set; }
}