// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingResourcesWatchStatus
{
    public int TrainingResourcesWatchStatusId { get; set; }

    public int? TrainingResourcesWatchStatusResourceId { get; set; }

    public bool? TrainingResourcesWatchStatusStatus { get; set; }

    public int? TrainingResourcesWatchStatusParticipantId { get; set; }

    public decimal? TrainingResourcesWatchStatusWatchTime { get; set; }

    public DateTime? TrainingResourcesWatchStatusCreatedDate { get; set; }

    public virtual TrainingParticipant TrainingResourcesWatchStatusParticipant { get; set; }

    public virtual TrainingCourseModuleResource TrainingResourcesWatchStatusResource { get; set; }
}