// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingCourseModuleResource
{
    public int TrainingCourseModuleResourcesId { get; set; }

    public int? TrainingCourseModuleResourcesModuleId { get; set; }

    public string TrainingCourseModuleResourcesType { get; set; }

    public string TrainingCourseModuleResourcesEname { get; set; }

    public string TrainingCourseModuleResourcesSname { get; set; }

    public string TrainingCourseModuleResourcesTname { get; set; }

    public string TrainingCourseModuleResourcesDescription { get; set; }

    public int? TrainingCourseModuleResourcesLanguageId { get; set; }

    public int? TrainingCourseModuleResourcesSequance { get; set; }

    public bool? TrainingCourseModuleResourcesIsOtherResource { get; set; }

    public string TrainingCourseModuleResourcesPath { get; set; }

    public TimeOnly? TrainingCourseModuleResourcesLength { get; set; }

    public bool? TrainingCourseModuleResourcesActive { get; set; }

    public DateTime? TrainingCourseModuleResourcesCreatedDate { get; set; }

    public virtual TrainingCourseModule TrainingCourseModuleResourcesModule { get; set; }

    public virtual ICollection<TrainingResourcesWatchStatus> TrainingResourcesWatchStatuses { get; set; } = new List<TrainingResourcesWatchStatus>();
}