// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingParticipant
{
    public int TrainingParticipantId { get; set; }

    public int? TrainingParticipantTrainingSheduleId { get; set; }

    public string TrainingParticipantEpf { get; set; }

    public string TrainingParticipantFname { get; set; }

    public string TrainingParticipantLname { get; set; }

    public string TrainingParticipantDepartment { get; set; }

    public string TrainingParticipantDesignation { get; set; }

    public bool? TrainingParticipantActive { get; set; }

    public int? TrainingParticipantDeletedReasonId { get; set; }

    public bool? TrainingParticipantIsTransfered { get; set; }

    public virtual TrainingParticipantDeletedReason TrainingParticipantDeletedReason { get; set; }

    public virtual TrainingShedule TrainingParticipantTrainingShedule { get; set; }

    public virtual ICollection<TrainingQuestionAttempt> TrainingQuestionAttempts { get; set; } = new List<TrainingQuestionAttempt>();

    public virtual ICollection<TrainingQuizAttempt> TrainingQuizAttempts { get; set; } = new List<TrainingQuizAttempt>();

    public virtual ICollection<TrainingResourcesWatchStatus> TrainingResourcesWatchStatuses { get; set; } = new List<TrainingResourcesWatchStatus>();
}