// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingShedule
{
    public int TrainingSheduleId { get; set; }

    public int? TrainingSheduleTrainingCourseId { get; set; }

    public int? TrainingSheduleTrainerId { get; set; }

    public string TrainingSheduleName { get; set; }

    public string TrainingSheduleDescription { get; set; }

    public DateTime? TrainingSheduleStartDate { get; set; }

    public DateTime? TrainingSheduleEndDate { get; set; }

    public int? TrainingSheduleParticipantCount { get; set; }

    public bool? TrainingSheduleIsComplete { get; set; }

    public bool? TrainingSheduleActive { get; set; }

    public DateTime? TrainingSheduleCreatedDate { get; set; }

    public virtual ICollection<TrainingParticipant> TrainingParticipants { get; set; } = new List<TrainingParticipant>();

    public virtual Trainer TrainingSheduleTrainer { get; set; }

    public virtual TrainingCourse TrainingSheduleTrainingCourse { get; set; }
}