// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingQuiz
{
    public int TrainingQuizId { get; set; }

    public int? TrainingQuizModuleId { get; set; }

    public int? TrainingQuizNoOfAnswerRequired { get; set; }

    public string TrainingQuizEname { get; set; }

    public string TrainingQuizSname { get; set; }

    public string TrainingQuizTname { get; set; }

    public int? TrainingQuizAttemptCount { get; set; }

    public bool? TrainingQuizActive { get; set; }

    public DateTime? TrainingQuizCreatedDate { get; set; }

    public virtual ICollection<TrainingQuestionAttempt> TrainingQuestionAttempts { get; set; } = new List<TrainingQuestionAttempt>();

    public virtual ICollection<TrainingQuestion> TrainingQuestions { get; set; } = new List<TrainingQuestion>();

    public virtual ICollection<TrainingQuizAttempt> TrainingQuizAttempts { get; set; } = new List<TrainingQuizAttempt>();

    public virtual TrainingCourseModule TrainingQuizModule { get; set; }

    public virtual ICollection<TrainingStatus> TrainingStatuses { get; set; } = new List<TrainingStatus>();
}