// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingCourse
{
    public int TrainingCourseId { get; set; }

    public int? TrainingCourseTrainingId { get; set; }

    public int? TrainingCourseTrainerId { get; set; }

    public string TrainingCourseEname { get; set; }

    public string TrainingCourseSname { get; set; }

    public string TrainingCourseTname { get; set; }

    public string TrainingCourseDescription { get; set; }

    public int? TrainingCourseSequance { get; set; }

    public bool? TrainingCourseActive { get; set; }

    public DateTime? TrainingCourseCreatedDate { get; set; }

    public virtual ICollection<TrainingCourseModule> TrainingCourseModules { get; set; } = new List<TrainingCourseModule>();

    public virtual Trainer TrainingCourseTrainer { get; set; }

    public virtual Training TrainingCourseTraining { get; set; }

    public virtual ICollection<TrainingShedule> TrainingShedules { get; set; } = new List<TrainingShedule>();

    public virtual ICollection<TrainingStatus> TrainingStatuses { get; set; } = new List<TrainingStatus>();
}