// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingQuestion
{
    public int TrainingQuestionId { get; set; }

    public int? TrainingQuestionQuizId { get; set; }

    public string TrainingQuestionEname { get; set; }

    public string TrainingQuestionSname { get; set; }

    public string TrainingQuestionTname { get; set; }

    public bool? TrainingQuestionActive { get; set; }

    public DateTime? TrainingQuestionCreatedDate { get; set; }

    public virtual ICollection<TrainingQuestionAnswer> TrainingQuestionAnswers { get; set; } = new List<TrainingQuestionAnswer>();

    public virtual ICollection<TrainingQuestionAttempt> TrainingQuestionAttempts { get; set; } = new List<TrainingQuestionAttempt>();

    public virtual TrainingQuestionCorrectAnswer TrainingQuestionCorrectAnswer { get; set; }

    public virtual TrainingQuiz TrainingQuestionQuiz { get; set; }
}