// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingCourseModule
{
    public int TrainingCourseModuleId { get; set; }

    public int? TrainingCourseModuleTrainingCourseId { get; set; }

    public string TrainingCourseModuleEname { get; set; }

    public string TrainingCourseModuleSname { get; set; }

    public string TrainingCourseModuleTname { get; set; }

    public string TrainingCourseModuleDescription { get; set; }

    public int? TrainingCourseModuleSequance { get; set; }

    public bool? TrainingCourseModuleIsQuiz { get; set; }

    public int? TrainingCourseModuleQuizTypeId { get; set; }

    public bool? TrainingCourseModuleActive { get; set; }

    public DateTime? TrainingCourseModuleCreatedDate { get; set; }

    public virtual QuizType TrainingCourseModuleQuizType { get; set; }

    public virtual ICollection<TrainingCourseModuleResource> TrainingCourseModuleResources { get; set; } = new List<TrainingCourseModuleResource>();

    public virtual TrainingCourse TrainingCourseModuleTrainingCourse { get; set; }

    public virtual ICollection<TrainingQuiz> TrainingQuizzes { get; set; } = new List<TrainingQuiz>();

    public virtual ICollection<TrainingStatus> TrainingStatuses { get; set; } = new List<TrainingStatus>();
}