// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingQuestionAnswer
{
    public int TrainingQanswerId { get; set; }

    public int? TrainingQanswerQuestionId { get; set; }

    public string TrainingQanswerEname { get; set; }

    public string TrainingQanswerSname { get; set; }

    public string TrainingQanswerTname { get; set; }

    public bool? TrainingQanswerActive { get; set; }

    public DateTime? TrainingQanswerCreatedDate { get; set; }

    public virtual TrainingQuestion TrainingQanswerQuestion { get; set; }

    public virtual ICollection<TrainingQuestionCorrectAnswer> TrainingQuestionCorrectAnswers { get; set; } = new List<TrainingQuestionCorrectAnswer>();
}