// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingParticipantDeletedReason
{
    public int TrainingParticipantDeletedRId { get; set; }

    public string TrainingParticipantDeletedRReason { get; set; }

    public bool? TrainingParticipantDeletedRActive { get; set; }

    public DateTime? TrainingParticipantDeletedRCreatedDate { get; set; }

    public virtual ICollection<TrainingParticipant> TrainingParticipants { get; set; } = new List<TrainingParticipant>();
}