// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingQuizAttempt
{
    public int TrainingQuizAttemptId { get; set; }

    public int? TrainingQuizAttemptQuizId { get; set; }

    public int? TrainingQuizAttemptParticipantId { get; set; }

    public int? TrainingQuizAttemptMarks { get; set; }

    public virtual ICollection<TrainingQuestionAttempt> TrainingQuestionAttempts { get; set; } = new List<TrainingQuestionAttempt>();

    public virtual TrainingParticipant TrainingQuizAttemptParticipant { get; set; }

    public virtual TrainingQuiz TrainingQuizAttemptQuiz { get; set; }
}