// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class Training
{
    public int TrainingId { get; set; }

    public string TrainingEname { get; set; }

    public string TrainingSname { get; set; }

    public string TrainingTname { get; set; }

    public string TrainingDescription { get; set; }

    public string TrainingType { get; set; }

    public bool? TrainingActive { get; set; }

    public DateTime? TrainingCreatedDate { get; set; }

    public virtual ICollection<TrainingCourse> TrainingCourses { get; set; } = new List<TrainingCourse>();

    public virtual ICollection<TrainingStatus> TrainingStatuses { get; set; } = new List<TrainingStatus>();
}