// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class Trainer
{
    public int TrainerId { get; set; }

    public string TrainerType { get; set; }

    public string TrainerEpf { get; set; }

    public string TrainerFname { get; set; }

    public string TrainerLname { get; set; }

    public string TrainerDepartment { get; set; }

    public string TrainerDesignation { get; set; }

    public bool? TrainerActive { get; set; }

    public DateTime? TrainerCreatedDate { get; set; }

    public virtual ICollection<TrainingCourse> TrainingCourses { get; set; } = new List<TrainingCourse>();
}