// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingParticipantTransfer
{
    public int TrainingParticipantTransferId { get; set; }

    public int? TrainingParticipantTransferOldShduleid { get; set; }

    public DateTime? TrainingParticipantTransferTransferedDate { get; set; }

    public int? TrainingParticipantTransferNewSheduleId { get; set; }

    public bool? TrainingParticipantTransferActive { get; set; }
}