// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningManagementSystem.Data.LMSModels;

public partial class TrainingQuestionAttempt
{
    public int TrainingQattempId { get; set; }

    public int? TrainingQattempQuizId { get; set; }

    public int? TrainingQattempParticipantId { get; set; }

    public int? TrainingQattempQuestionId { get; set; }

    public int? TrainingQattempQuestionAnswerId { get; set; }

    public int? TrainingQattempQuizAttempId { get; set; }

    public virtual TrainingParticipant TrainingQattempParticipant { get; set; }

    public virtual TrainingQuestion TrainingQattempQuestion { get; set; }

    public virtual TrainingQuiz TrainingQattempQuiz { get; set; }

    public virtual TrainingQuizAttempt TrainingQattempQuizAttemp { get; set; }
}